# Generated by Django 3.0.6 on 2020-05-15 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
