# Generated by Django 3.0.6 on 2020-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200515_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='email',
            field=models.EmailField(blank=True, default='pavan@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='mobile_number',
            field=models.CharField(blank=True, default=8892402343, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='name',
            field=models.CharField(blank=True, default='test', max_length=250),
            preserve_default=False,
        ),
    ]
