# Generated by Django 3.0.6 on 2020-05-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200515_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='active',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='age',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='name',
        ),
    ]
