# Generated by Django 3.0.6 on 2020-05-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('testapp', '0006_auto_20200515_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='user_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
