# Generated by Django 3.0.6 on 2020-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_employeedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='number',
            field=models.IntegerField(default=8892456783),
            preserve_default=False,
        ),
    ]
