# Generated by Django 3.0.6 on 2020-05-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usersdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersDetails',
        ),
    ]
