# Generated by Django 3.0.6 on 2020-05-15 06:50

from django.db import migrations, models
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_usersdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default='Testing '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
